### ISSUE TITLE
Unable to create tfrecord

### ISSUE THREAD

**Issue by Atul997** [datitran/raccoon_dataset#12]
hi, 
i created train_labels.csv and test_labels.csv files and when i run the script 
**generate_tfrecord.py** it throws me error- 
`tensorflow.python.framework.errors_impl.NotFoundError: /home/ob/images/car49`

I checked for that file but it is available there, then i run script deleting that row from csv file and same error came for car48.

How can i resolve this?

**Comment by rabarona** [comment]
Hi @Atul997,

The script is taking the folder from where you are running generate_tfrecord.py, in this case, seems to be  `/home/atul/ob/`. Try creating a folder images an put all the images there. 

It worked for me, but what I did was to modify the script to accept a parameter for the images folder.

Hope this helps.

**Comment by Atul997** [comment]
Thanks for ur reply, but i reslove this earlier at my end 😊


-Atul

**Comment by hanaskuliah** [comment]
hi @Atul997 could you explain how you solve this problem?

**Comment by NagrajSrivatsa** [comment]
Traceback (most recent call last):
  File "generate_tfrecord.py", line 100, in <module>
    tf.app.run()
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "generate_tfrecord.py", line 91, in main
    tf_example = create_tf_example(group, path)
  File "generate_tfrecord.py", line 46, in create_tf_example
    encoded_jpg = fid.read()
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 119, in read
    self._preread_check()
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 79, in _preread_ch
eck
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __e
xit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /home/ec2-user/sample-notebooks/object-detection/image/IMG_20171211_133838 - Copy; No suc
h file or directory
sh-4.2$ python3 xml_
my images have been annotated iam able to create csv file but not able to create tfrecords

**Comment by NagrajSrivatsa** [comment]
Any help will be appreciated.Thankyou

**Comment by yash-bhat** [comment]
Hi @Atul997 ,

I have similar issue.
How did you resolve it?
My images are placed in folder my script is running from. And yet it isn't accessed!

**Comment by Atul997** [comment]
What exact problem u r facing ??

**Comment by yash-bhat** [comment]
@Atul997 
Hello,
I fixed the issue.
The extension of the training images are not specified when 'xml_to_csv' is done. (.png in my case)
My dataset is smaller so I just changed it in the csv file manually and rerun ... andit worked!
This may have to be incorporated in the 'xml_to_csv' script.
Anyway, Thank you:)

**Comment by Technebby** [comment]
@Atul997  i am having this issue...aplease help in sorting this out

Traceback (most recent call last):
File "F:/Object_detection/generate_tfrecord.py", line 98, in 
tf.app.run()
File "C:\Users\Harjeet\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
_sys.exit(main(argv))
File "F:/Object_detection/generate_tfrecord.py", line 89, in main
tf_example = create_tf_example(group, path)
File "F:/Object_detection/generate_tfrecord.py", line 44, in create_tf_example
encoded_jpg = fid.read()
File "C:\Users\Harjeet\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 120, in read
self._preread_check()
File "C:\Users\Harjeet\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 80, in _preread_check
compat.as_bytes(self.__name), 1024 * 512, status)
File "C:\Users\Harjeet\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 516, in exit
c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: F:\Object_detection\images\pic3.jpeg : The system cannot find the file specified.
; No such file or directory

**Comment by Atul997** [comment]
Pls chk that image is inside the specified folder or not. Keep all the
images inside a folder and then re-run the code. Hope it helps.
----

**Comment by Technebby** [comment]
@Atul997  thanks for the valuable comment, i was doing it wrong all together. it worked for me 

thanks once again for the help.

**Comment by Atul997** [comment]
Your welcome☺️

**Comment by Hashirroshan** [comment]
While running Generat_tfrecord.py,  it says some images are not found in the directory even I using raccoon images and the same steps done by datitran. Pls help me to solve this

**Comment by M1thun** [comment]
yeah!! it was because the csv file didnt had some image names with extension(jpg in my case), so manually edited the csv file and it worked.
Thanks

**Comment by BasitJaved** [comment]
Guys make sure your csv file contain file name with extension .jpg if still there is error you can follow code below, thats how I solved this problem

python3 generate_tf_record.py --csv_input=data/train_labels.csv --output_path=train.record
python3 generate_tf_record.py --csv_input=data/test_labels.csv --output_path=test.record

all the images were in one folder i.e images and flags were as below

flags.DEFINE_string('csv_input', '','data/train_labels.csv')
flags.DEFINE_string('output_path','', 'train.record')
flags.DEFINE_string('image_dir', '', 'images')

I saved record file in main folder and later copied it to data folder

**Comment by saikaushik0410** [comment]
> @Atul997
> Hello,
> I fixed the issue.
> The extension of the training images are not specified when 'xml_to_csv' is done. (.png in my case)
> My dataset is smaller so I just changed it in the csv file manually and rerun ... andit worked!
> This may have to be incorporated in the 'xml_to_csv' script.
> Anyway, Thank you:)

can u explain how did u do it?

**Comment by joel1895** [comment]
# Create train data:
  python generate_tfrecord.py --csv_input=data/train_labels.csv  --output_path=data/train.record  --image_dir=images/train/


  # Create test data:
  python generate_tfrecord.py --csv_input=data/test_labels.csv  --output_path=data/test.record  --image_dir=images/test/

try this, worked for me

**Comment by vishaymalhotra** [comment]
> # Create train data:
> 
>   python generate_tfrecord.py --csv_input=data/train_labels.csv  --output_path=data/train.record  --image_dir=images/train/
> 
> 
> 
> 
> 
>   # Create test data:
> 
>   python generate_tfrecord.py --csv_input=data/test_labels.csv  --output_path=data/test.record  --image_dir=images/test/
> 
> 
> 
> try this, worked for me
> 
> 

Hey where we have to write this code?

**Comment by HridoyHazard** [comment]
i solved this issue by rename correctly the xml file (inside of it) and the image file. both have to be in same name otherwise you can't generate tfrecord.

**Comment by alrappie** [comment]
I solved this issue by rewrite the XML file

for xml_file in glob.glob(path + '/*.xml'):
    file_names = xml_file.split('\\')[1]
    tree = ET.parse(xml_file)
    root = tree.getroot()
    filename = root.find('filename').text+'.JPEG'
    root.find('filename').text = filename
    root.insert(2,ET.fromstring(f'<path>{os.path.join(path,filename)}</path>'))
    tree.write(file_names)
