### ISSUE TITLE
Error occurs when using generate_tfrecord.py

### ISSUE THREAD

**Issue by limkuoysuong** [datitran/raccoon_dataset#15]
This is the error I got when running generate_tfrecord.py

Traceback (most recent call last):
  File "generate_tfrecord_main.py", line 104, in <module>
    tf.app.run()
  File "/home/suong/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "generate_tfrecord_main.py", line 90, in main
    writer = tf.python_io.TFRecordWriter(FLAGS.output_path)
  File "/home/suong/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/flags.py", line 50, in __getattr__
    raise AttributeError(name)
AttributeError: output_path

Could anyone help me with this?

**Comment by datitran** [comment]
This can't be the full error? What is output_path?

**Comment by ucesfpa** [comment]
Hello, I had the same problem:

File "C:\Users\ucesfpa\Object_Detection\models-master\research\raccoon_dataset-master\generate_tfrecord.py", line 85, in main
    writer = tf.python_io.TFRecordWriter(FLAGS.output_path)
  File "C:\Users\ucesfpa\Anaconda3\envs\deeplearning\lib\site-packages\tensorflow\python\platform\flags.py", line 55, in __getattr__
    raise AttributeError(name)
AttributeError: output_path


It looks like there is a problem in the file flags.py at the line highlited with "<<<---"

  
def __getattr__(self, name):
    """Retrieves the 'value' attribute of the flag --name."""
    try:
      parsed = self.__dict__['__parsed']
    except KeyError:
      # May happen during pickle.load or copy.copy
      raise AttributeError(name)
    if not parsed:
      self._parse_flags()
    if name not in self.__dict__['__flags']:
      raise AttributeError(name)   <<<<--------
    return self.__dict__['__flags'][name]


Can you Help me in solving this problem??

Regards,
Fabio
