### ISSUE TITLE
Can't generate TF Records

### ISSUE THREAD

**Issue by rafaellehmkuhl** [datitran/raccoon_dataset#16]
When I try to generate the TF record files, i get the following:

```
Traceback (most recent call last):
  File "generate_tfrecord.py", line 99, in <module>
    tf.app.run()
  File "/home/rafael/.virtualenvs/py3cv3/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "generate_tfrecord.py", line 90, in main
    tf_example = create_tf_example(group, path)
  File "generate_tfrecord.py", line 45, in create_tf_example
    encoded_jpg = fid.read()
  File "/home/rafael/.virtualenvs/py3cv3/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 118, in read
    self._preread_check()
  File "/home/rafael/.virtualenvs/py3cv3/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 78, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/rafael/.virtualenvs/py3cv3/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: /home/rafael/PersonalProjects/git/RetrainedObjectDetector/images/raccoon-76.png

```

This is the command I use to call the function:

`python generate_tfrecord.py --csv_input=data/train_labels.csv --output_path=data/train.record`

**Comment by datitran** [comment]
From the error my best guess is that the file is not there?

**Comment by rafaellehmkuhl** [comment]
It seems like the labels.csv files where generated with the .png extension, while the images are .jpeg. I just saw your folders and the labels.csv all contain .jpeg labels. It must be some problem with my xml_to_csv.py, since I changed it and created the labels through it.

Will take a look and come back with answers.

**Comment by datitran** [comment]
It doesn't matter if it is .png or .jpeg in the xml files. The only thing that matters is if the filename is correct in the csv file. Other than that I didn't experience any problem with this.

**Comment by anlamlibisey** [comment]
i get the same error. i have checked all file extensions, they are matched. jpg file in directory jpg in cvs files.

**Comment by ActiveNeuron** [comment]
Even am facing the same issue!! Anyone with solution???????????

**Comment by Qryptoc** [comment]
Like @rafaellehmkuhl said my .xml files had .png extensions in them (while the actual images had .jpg) and this got automatically transferred to the .csv files (probably while batch processing them). A quick fix was to change the extensions in the .csv files.

**Comment by Aishwarya2203** [comment]
I'm facing the same problem
i cannot generate the tf.recored file 




Microsoft Windows [Version 10.0.18262.1000]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\admin\Desktop\object-detection>python generate_tfrecord.py
Traceback (most recent call last):
  File "generate_tfrecord.py", line 99, in <module>
    tf.app.run()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "generate_tfrecord.py", line 85, in main
    writer = tf.python_io.TFRecordWriter(FLAGS.output_path)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\lib\io\tf_record.py", line 112, in __init__
    compat.as_bytes(path), compat.as_bytes(compression_type), status)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 526, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a NewWriteableFile:  : The system cannot find the path specified.
; No such process

C:\Users\admin\Desktop\object-detection>python generate_tfrecord.py

**Comment by Aishwarya2203** [comment]
> Like @rafaellehmkuhl said my .xml files had .png extensions in them (while the actual images had .jpg) and this got automatically transferred to the .csv files (probably while batch processing them). A quick fix was to change the extensions in the .csv files.

i have all the extensions in the file csv file as .JPG could that be a problem, but my original image also has the same extension

**Comment by fariha123** [comment]
Facing the same issue, anyone found a solution?
