### ISSUE TITLE
creating tfrecords

### ISSUE THREAD

**Issue by onlyak** [datitran/raccoon_dataset#17]
Traceback (most recent call last):
  File "generate_record.py", line 99, in <module>
    tf.app.run()
  File "/home/ameya/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "generate_record.py", line 90, in main
    tf_example = create_tf_example(group, path)
  File "generate_record.py", line 79, in create_tf_example
    'image/object/class/label': dataset_util.int64_list_feature(classes),
  File "/home/ameya/anaconda3/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/utils/dataset_util.py", line 26, in int64_list_feature
TypeError: None has type NoneType, but expected one of: int, long﻿

**Comment by datitran** [comment]
Looks like you need to adjust the classes.

**Comment by Downlosc** [comment]
Did you solve this?
