### ISSUE TITLE
generate_tfrecords

### ISSUE THREAD

**Issue by swetshaw** [datitran/raccoon_dataset#23]
Traceback (most recent call last):
  File "generate_tfrecord.py", line 105, in <module>
    tf.app.run()
  File "C:\Users\24651\anaconda\lib\site-packages\tensorflow\python\platform\app
.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "generate_tfrecord.py", line 96, in main
    tf_example = create_tf_example(group, path)
  File "generate_tfrecord.py", line 51, in create_tf_example
    encoded_jpg = fid.read()
  File "C:\Users\24651\anaconda\lib\site-packages\tensorflow\python\lib\io\file_
io.py", line 118, in read
    self._preread_check()
  File "C:\Users\24651\anaconda\lib\site-packages\tensorflow\python\lib\io\file_
io.py", line 78, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "C:\Users\24651\anaconda\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "C:\Users\24651\anaconda\lib\site-packages\tensorflow\python\framework\er
rors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile faile
d to Create/Open: D:\object size measurement\dataset\training\images\object__29.
jpg : The system cannot find the path specified.

**Comment by datitran** [comment]
The error says that it cannot find the file.

**Comment by RenukaNale** [comment]
same error any idea how do I solve it.  
I am beginner in deep learning I am little bit confuse after training we check accuracy on  test set(here which images should I used label or unlable, according to me it should be unlable)

**Comment by RenukaNale** [comment]
Hello,
I am using your script for generating tfrecord on my own dataset getting following error any idea how I solve it. I am able to convert from xmltocsv.

filename | width | height | class | xmin | ymin | xmax | ymax |  
-- | -- | -- | -- | -- | -- | -- | -- | --
100.png | 1287 | 930 | fillet | 396 | 666 | 445 | 799 |  
100.png | 1287 | 930 | fillet | 368 | 740 | 558 | 783 |  
But getting following error while converting to tfrecord

Traceback (most recent call last):
  File "generate_tfrecord.py", line 100, in <module>
    tf.app.run()
  File "C:\Users\Sanjay_pc\python35\lib\site-packages\tensorflow\python\platform
\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "generate_tfrecord.py", line 91, in main
    tf_example = create_tf_example(group, path)
  File "generate_tfrecord.py", line 80, in create_tf_example
    'image/object/class/label': dataset_util.int64_list_feature(classes),
  File "C:\Users\Sanjay_pc\python35\pythonprograming\Object_Detection\dataset_ut
il.py", line 9, in int64_list_feature
    return tf.train.Feature(int64_list=tf.train.Int64List(value=value))
  File "C:\Users\Sanjay_pc\python35\lib\site-packages\google\protobuf\internal\p
ython_message.py", line 509, in init
    copy.extend(field_value)
  File "C:\Users\Sanjay_pc\python35\lib\site-packages\google\protobuf\internal\c
ontainers.py", line 275, in extend
    new_values = [self._type_checker.CheckValue(elem) for elem in elem_seq_iter]

  File "C:\Users\Sanjay_pc\python35\lib\site-packages\google\protobuf\internal\c
ontainers.py", line 275, in <listcomp>
    new_values = [self._type_checker.CheckValue(elem) for elem in elem_seq_iter]

  File "C:\Users\Sanjay_pc\python35\lib\site-packages\google\protobuf\internal\t
ype_checkers.py", line 133, in CheckValue
    raise TypeError(message)
TypeError: None has type <class 'NoneType'>, but expected one of: (<class 'int'>
,)

**Comment by RenukaNale** [comment]
problem solved my mistake while annotating spelling mistake
