### ISSUE TITLE
Issue while running generate_tfrecord.py

### ISSUE THREAD

**Issue by soumy94** [datitran/raccoon_dataset#33]
I have created the dataset to generate tfrecord files:

and ran this command: python generate_tfrecord.py --csv_input=data/traindata_labels.csv --output_path/train.record

Traceback (most recent call last):
  File "generate_tfrecord.py", line 100, in <module>
    tf.app.run()
  File "/home/soumya94/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "generate_tfrecord.py", line 86, in main
    writer = tf.python_io.TFRecordWriter(FLAGS.output_path)
  File "/home/soumya94/.local/lib/python2.7/site-packages/tensorflow/python/lib/io/tf_record.py", line 106, in __init__
    compat.as_bytes(path), compat.as_bytes(compression_type), status)
  File "/home/soumya94/.local/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: ; No such file or directory

I don't understand what I'm doing wrong.

**Comment by soumy94** [comment]
I had an error in my command
