### ISSUE TITLE
train_dir` is missing.

### ISSUE THREAD

**Issue by chandanmono** [datitran/raccoon_dataset#42]
While running 
python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v1_pets.config      i get an error as

WARNING:tensorflow:From D:\Mainproject\models-master\research\object_detection\trainer.py:228: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
Traceback (most recent call last):
  File "train.py", line 169, in <module>
    tf.app.run()
  File "C:\Users\Chandan\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 124, in run
    _sys.exit(main(argv))
  File "train.py", line 165, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "D:\Mainproject\models-master\research\object_detection\trainer.py", line 235, in train
    train_config.prefetch_queue_capacity, data_augmentation_options)
  File "D:\Mainproject\models-master\research\object_detection\trainer.py", line 59, in create_input_queue
    tensor_dict = create_tensor_dict_fn()
  File "train.py", line 122, in get_next
    worker_index=FLAGS.task)).get_next()
  File "D:\Mainproject\models-master\research\object_detection\builders\dataset_builder.py", line 140, in build
    label_map_proto_file=label_map_proto_file)
  File "D:\Mainproject\models-master\research\object_detection\data_decoders\tf_example_decoder.py", line 143, in __init__
    use_display_name)
  File "D:\Mainproject\models-master\research\object_detection\utils\label_map_util.py", line 149, in get_label_map_dict
    label_map = load_labelmap(label_map_path)
  File "D:\Mainproject\models-master\research\object_detection\utils\label_map_util.py", line 129, in load_labelmap
    label_map_string = fid.read()
  File "C:\Users\Chandan\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 119, in read
    self._preread_check()
  File "C:\Users\Chandan\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 79, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "C:\Users\Chandan\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnimplementedError: File system scheme gs not implemented

and when i run python train.py it generates a error

Traceback (most recent call last):
  File "train.py", line 169, in <module>
    tf.app.run()
  File "C:\Users\Chandan\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 124, in run
    _sys.exit(main(argv))
  File "train.py", line 88, in main
    assert FLAGS.train_dir, '`train_dir` is missing.'
AssertionError: `train_dir` is missing.

pls help...   thank u

**Comment by amritarana** [comment]
did you got the solution for this ?

**Comment by daleyprabhakar** [comment]
is there any resolution for this...because even i am facing a similar issue.
\ObjDetection Repository>train.py --logtostderr --train_dir = training/ --pipeline_config_path = training/coco.config

Traceback (most recent call last):
  File "C:\Users\s.prabhakar.daley\Desktop\ObjDetection Repository\train.py", line 184, in <module>
    tf.app.run()
  File "C:\Users\s.prabhakar.daley\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "C:\Users\s.prabhakar.daley\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 272, in new_func
    return func(*args, **kwargs)
  File "C:\Users\s.prabhakar.daley\Desktop\ObjDetection Repository\train.py", line 89, in main
    assert FLAGS.train_dir, '`train_dir` is missing.'
AssertionError: `train_dir` is missing.

**Comment by Telang8100** [comment]
did you got the solution for this ?

**Comment by pamrani** [comment]
same here, I also facing such !
