### ISSUE TITLE
training locally issue

### ISSUE THREAD

**Issue by ngksai93** [datitran/raccoon_dataset#43]
python object_detection/train.py --logtostderr=/home/gopalakrishna/log_dir --pipeline_config_path=/home/gopalakrishna/PathToConfig/ssd_mobilenet_v1_coco.config --train_dir=/home/gopalakrishna/model
/home/gopalakrishna/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "object_detection/train.py", line 167, in <module>
    tf.app.run()
  File "/home/gopalakrishna/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "object_detection/train.py", line 92, in main
    FLAGS.pipeline_config_path)
  File "/home/gopalakrishna/work/models-master/research/object_detection/utils/config_util.py", line 88, in get_configs_from_pipeline_file
    text_format.Merge(proto_str, pipeline_config)
  File "/home/gopalakrishna/anaconda2/lib/python2.7/site-packages/google/protobuf/text_format.py", line 533, in Merge
    descriptor_pool=descriptor_pool)
  File "/home/gopalakrishna/anaconda2/lib/python2.7/site-packages/google/protobuf/text_format.py", line 587, in MergeLines
    return parser.MergeLines(lines, message)
  File "/home/gopalakrishna/anaconda2/lib/python2.7/site-packages/google/protobuf/text_format.py", line 620, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/home/gopalakrishna/anaconda2/lib/python2.7/site-packages/google/protobuf/text_format.py", line 635, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/home/gopalakrishna/anaconda2/lib/python2.7/site-packages/google/protobuf/text_format.py", line 679, in _MergeField
    name = tokenizer.ConsumeIdentifierOrNumber()
  File "/home/gopalakrishna/anaconda2/lib/python2.7/site-packages/google/protobuf/text_format.py", line 1152, in ConsumeIdentifierOrNumber
    raise self.ParseError('Expected identifier or number, got %s.' % result)
google.protobuf.text_format.ParseError: 186:1 : Expected identifier or number, got ''.

**Comment by ngksai93** [comment]
i tried this with both tensorflow version 1.2 and 1.3 i got same issue( cpu only  and locally)

**Comment by Evaggelou** [comment]
How you solved it??
