### ISSUE TITLE
ModuleNotFoundError: No module named 'pycocotools._mask

### ISSUE THREAD

**Issue by aliBUT** [datitran/raccoon_dataset#48]
`C:\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "eval.py", line 50, in <module>
    from object_detection import evaluator
  File "C:\Continuum\research\object_detection\evaluator.py", line 27, in <module>
    from object_detection.metrics import coco_evaluation
  File "C:\Continuum\research\object_detection\metrics\coco_evaluation.py", line 20, in <module>
    from object_detection.metrics import coco_tools
  File "C:\Continuum\research\object_detection\metrics\coco_tools.py", line 47, in <module>
    from pycocotools import coco
  File "C:\Continuum\research\pycocotools\coco.py", line 55, in <module>
    from . import mask as maskUtils
  File "C:\Continuum\research\pycocotools\mask.py", line 3, in <module>
    import pycocotools._mask as _mask
ModuleNotFoundError: No module named 'pycocotools._mask'`

Hi i am following you tutorial , When i try to run eval script i get this error . Training script is working fine and all the scripts before eval.py

**Comment by aliBUT** [comment]
@datitran  any idea why this is happening?

**Comment by ViousGod** [comment]
why i run "python setup.py install" in cmd, it shows TypeError: unorderable types: NoneType() >= str()

**Comment by Purav-Zumkhawala** [comment]
@FalcoGer I am having the same problem while doing this in linux. Are Visual c++ tools supported for linux ? 
And is this the only workaround ?

**Comment by biendltb** [comment]
First, make sure you already installed the COCO API properly.

If you look inside the _model/research/_ folder, you will see the _pycocotools_ folder. Try to rename it to any other name.
The reason of this problem is that the code imported the _pycocotools_ from that folder, not from the installed folder that you just installed the COCO API.

**Comment by mihuzz** [comment]
### Hi, I have Error when run setup.py install. May be some one help me?
`\models\research\cocoapi\PythonAPI>python setup.py install
Compiling pycocotools/_mask.pyx because it changed.
[1/1] Cythonizing pycocotools/_mask.pyx
D:\Anaconda3\envs\sdk\lib\site-packages\Cython\Compiler\Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: D:\Lesson8\models\research\cocoapi\PythonAPI\pycocotools\_mask.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
running install
running build
running build_py
creating build
creating build\lib.win-amd64-3.6
creating build\lib.win-amd64-3.6\pycocotools
copying pycocotools\coco.py -> build\lib.win-amd64-3.6\pycocotools
copying pycocotools\cocoeval.py -> build\lib.win-amd64-3.6\pycocotools
copying pycocotools\mask.py -> build\lib.win-amd64-3.6\pycocotools
copying pycocotools\__init__.py -> build\lib.win-amd64-3.6\pycocotools
running build_ext
building 'pycocotools._mask' extension
creating build\temp.win-amd64-3.6
creating build\temp.win-amd64-3.6\Release
creating build\temp.win-amd64-3.6\Release\pycocotools
creating build\temp.win-amd64-3.6\common
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -ID:\Anaconda3\envs\sdk\lib\site-packages\numpy\core\include -I../common -ID:\Anaconda3\envs\sdk\include -ID:\Anaconda3\envs\sdk\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" /Tcpycocotools/_mask.c /Fobuild\temp.win-amd64-3.6\Release\pycocotools/_mask.obj
_mask.c
d:\anaconda3\envs\sdk\include\pyconfig.h(59): fatal error C1083: Не удается открыть файл включение: io.h: No such file or directory,
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2`

**Comment by amit-code** [comment]
You can replace extra_compile_args=['-Wno-cpp', '-Wno-unused-function', '-std=c99'] with extra_compile_args={'gcc': ['/Qstd=c99']} in ./libs/datasets/pycocotools/setup.py. maybe help

**Comment by kritoZhang** [comment]
> First, make sure you already installed the COCO API properly.
> 
> If you look inside the _model/research/_ folder, you will see the _pycocotools_ folder. Try to rename it to any other name.
> The reason of this problem is that the code imported the _pycocotools_ from that folder, not from the installed folder that you just installed the COCO API.

totally correct!

**Comment by durgauestc** [comment]
ModuleNotFoundError: No module named 'pycocotools'
how to solve this in mmdetection
