### ISSUE TITLE
error while xml_to_csv

### ISSUE THREAD

**Issue by andhana** [datitran/raccoon_dataset#49]
$ python xml_to_csv2.py 
Traceback (most recent call last):
  File "xml_to_csv2.py", line 35, in <module>
    main()
  File "xml_to_csv2.py", line 30, in main
    xml_df = xml_to_csv(image_path)
  File "xml_to_csv2.py", line 10, in xml_to_csv
    tree = ET.parse(xml_file)
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 1195, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 596, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: mismatched tag: line 2, column 21

I have 713 .xml files

**Comment by gunjan5489** [comment]
File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 1184, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 596, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0


Im facing the same error , please help
