### ISSUE TITLE
error in generate tfrecord

### ISSUE THREAD

**Issue by xxbb1234021** [datitran/raccoon_dataset#53]
hi all , when I run generate_tfrecord. I met the problem below:

Traceback (most recent call last):
  File "D:/workspaces/python/chartbot/generate_tfrecord.py", line 99, in <module>
    tf.app.run()
  File "C:\Users\kevin\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "D:/workspaces/python/chartbot/generate_tfrecord.py", line 90, in main
    tf_example = create_tf_example(group, path)
  File "D:/workspaces/python/chartbot/generate_tfrecord.py", line 79, in create_tf_example
    'image/object/class/label': dataset_util.int64_list_feature(classes)
  File "D:\workspaces\models\research\object_detection\utils\dataset_util.py", line 26, in int64_list_feature
    return tf.train.Feature(int64_list=tf.train.Int64List(value=value))
TypeError: None has type NoneType, but expected one of: int, long

how can i fix it?

**Comment by kevintomsgithub** [comment]
I am facing the same error, how did you get it fixed?

**Comment by xxbb1234021** [comment]
Thanks,i fix it

**Comment by Thommy257** [comment]
and how did you do that?

**Comment by ali0517** [comment]
how did you fix it? @xxbb1234021

**Comment by zq1314** [comment]
how did you do that? @xxbb1234021

**Comment by xxbb1234021** [comment]
@zq1314 
https://github.com/datitran/raccoon_dataset/issues/2

**Comment by unaisshazan** [comment]
![desk 54](https://user-images.githubusercontent.com/51183141/58603608-d9b3c800-82aa-11e9-82d7-bd400b68d48c.PNG)
 help please how to sort this problem

**Comment by Shiva0072** [comment]
> This means that there is one class that is not captured. Maybe you have a spelling error in one of your class or there is really some classes that you haven't put in the function yet. Try to check this again.

This was really the case with me. Just check your generateTFRecord.py file. In my case there were 9 labels mentioned with different names, But I was trying to use this file for 2 labels only. Changed the label numbers and their classes. then worked fine.
