### ISSUE TITLE
no such file or directory

### ISSUE THREAD

**Issue by mohammad69h94** [datitran/raccoon_dataset#55]
When converting to tf_record, I will deal with the following problem:
![untitled](https://user-images.githubusercontent.com/36889021/39392585-8a029158-4acd-11e8-9db1-f226c6951846.jpg)

**Comment by LeeroyJK** [comment]
Same issue here

**Comment by Technebby** [comment]
same issue here also, anybody got any solution of this problem please help

Traceback (most recent call last):
File "F:/Object_detection/generate_tfrecord.py", line 98, in 
tf.app.run()
File "C:\Users\Harjeet\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
_sys.exit(main(argv))
File "F:/Object_detection/generate_tfrecord.py", line 89, in main
tf_example = create_tf_example(group, path)
File "F:/Object_detection/generate_tfrecord.py", line 44, in create_tf_example
encoded_jpg = fid.read()
File "C:\Users\Harjeet\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 120, in read
self._preread_check()
File "C:\Users\Harjeet\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 80, in _preread_check
compat.as_bytes(self.__name), 1024 * 512, status)
File "C:\Users\Harjeet\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 516, in exit
c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: F:\Object_detection\images\pic3.jpeg : The system cannot find the file specified.
; No such file or directory

**Comment by Phantiminium** [comment]
I had this problem too, and I was able to successfully run this code by going into the xml_to_csv.py code and adding "+ ".jpg" " before the comma.

**Comment by Phantiminium** [comment]
I had this problem too, and I was able to successfully run this code by going into the xml_to_csv.py code and adding "+ ".jpg" " before the comma on line 13, running the xml_to_csv.py again, and then running tf_record.

**Comment by nadzranasinghe** [comment]
same issue here

**Comment by nadzranasinghe** [comment]
> When converting to tf_record, I will deal with the following problem:
> ![untitled](https://user-images.githubusercontent.com/36889021/39392585-8a029158-4acd-11e8-9db1-f226c6951846.jpg)

Check your path, check whether you have the image 0000000.jpg is inside images.

**Comment by adityasinghal2** [comment]
I had this problem too, just add  --imageDir={path to image dir}
Problem will be solved..

**Comment by skiteskopes** [comment]
@adityasinghal2 you mean for example I would have something like this? 
    python generate_tfrecord.py --csv_input=data/train_labels.csv  --output_path=train.record --imageDir={C:\Users\billz\Desktop\object_detection\images}

**Comment by adityasinghal2** [comment]
@skiteskopes just remove that curly braces in --imageDir
i .e python generate_tfrecord.py --csv_input=data/train_labels.csv --output_path=train.record --imageDir=C:\Users\billz\Desktop\object_detection\images

**Comment by awaisumar1** [comment]
i have the same issue even after setting the imageDir={image path/train}
@adityasinghal2  @skiteskopes  were you able to solve it?
