### ISSUE TITLE
ModuleNotFoundError: No module named 'object_detection'

### ISSUE THREAD

**Issue by LeeyMessi** [datitran/raccoon_dataset#58]
I am using Win10 and Spyder, I have tried to run : generate_tfrecord.py, Unfortunately，shows "ModuleNotFoundError: No module named 'object_detection'", I guess the problem is the path, how to set the path in spyder?

**Comment by lidderdj** [comment]
I'm hitting this hurdle too. Same environment.

**Comment by Insertfunnylogin** [comment]
not sure concerning windows, but on Ubuntu you have to deploy object detection module by running setup.py from the research folder, then set PYTHONPATH accordingly
please check the tensorflow github for the correct run command configuration

**Comment by agriardyan** [comment]
I've managed to solve this problem in my system (win 10). The solution is not very straightforward but here : 

1. First u need to clone Tensorflow Object Detection API repository https://github.com/tensorflow/models. 
2. Follow the installation provided in https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md
3. In the step 2, you are required to compile protobuf library, so download the protobuf compiler at https://github.com/google/protobuf/releases/latest
4. Append the PYTHONPATH environment variable with the directory of <your cloned tensorflow object detection api>/research/slim (dont forget to add the PYTHONPATH to Path if you haven't done so.
5. No more ModuleNotFoundError: No module named 'object_detection'

**Comment by mbhurtel** [comment]
> on win10 go to ( \model master\models-master\research) open cmd in this path and type `python setup.py install`
> it should work

Thank you. It worked. (y)

**Comment by vanhoangns123** [comment]
please show me the path of win 10 go to ( \model master\models-master\research)  im newbie

**Comment by yo-carthy** [comment]
> > on win10 go to ( \model master\models-master\research) open cmd in this path and type `python setup.py install`
> > it should work
> 
> Thank you. It worked. (y)

Me too! Thanks

**Comment by shiko10** [comment]
> on win10 go to ( \model master\models-master\research) open cmd in this path and type `python setup.py install`
> it should work

is that path is found in Tensorflow Object Detection API repository ???

**Comment by raedkit** [comment]
Hi, you have to do the following commands to make it work for you :
`protoc object_detection/protos/*.proto --python_out=.`
Add the following to your ~/.bashrc : 
`export PYTHONPATH=$PYTHONPATH:<PATH_TO_TF>/TensorFlow/models/research/object_detection:<PATH_TO_TF>/TensorFlow/models/research:<PATH_TO_TF>/TensorFlow/models/research/slim`

**Comment by yashmodi123** [comment]
thank you its literally worked

**Comment by patrick-code-dev** [comment]
**pip install tensorflow-object-detection-api**

**Comment by ShahirAnsari** [comment]
Adding the full path to the object detection module solved the error in my case

`import sys`
`sys.path.append(..../full_path_to_object_detection_module/)`

**Comment by armansamimi** [comment]
> **pip install tensorflow-object-detection-api**

it did work, thanks so much

**Comment by Jayanth1812** [comment]
Hi, I am getting the following errors.. when I run the main training program..
(tensorflow) C:\tensorflow\models\research\object_detection>python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config
Traceback (most recent call last):
File "train.py", line 54, in
from object_detection.builders import model_builder
File "C:\tensorflow\models\research\object_detection\builders\model_builder.py", line 20, in
from object_detection.builders import anchor_generator_builder
File "C:\tensorflow\models\research\object_detection\builders\anchor_generator_builder.py", line 23, in
from object_detection.anchor_generators import flexible_grid_anchor_generator
ModuleNotFoundError: No module named 'object_detection.anchor_generators'

**Comment by zeelsheladiya** [comment]
i got this error while i was trying to run this code. and i have already installed tensorflow package from conda. what shuld i di to solve this error?

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-8-fd28d0a39720> in <module>
      1 import tensorflow as tf
----> 2 from object_detection.utils import config_util
      3 from object_detection.protos import pipeline_pb2
      4 from google.protobuf import text_format

ModuleNotFoundError: No module named 'object_detection'
