### ISSUE TITLE
unable complete Generatetfrecords.py

### ISSUE THREAD

**Issue by Hashirroshan** [datitran/raccoon_dataset#64]
after following all  steps mentioned by dar itran , i got following errors even after put return 0 instead of none.

pi@pi-HP-280-G1-MT:~/Downloads/new$ source activate tensorflow
(tensorflow) pi@pi-HP-280-G1-MT:~/Downloads/new$ python3 generate_tfrecord.py --csv_input=data/test_labels.csv  --output_path=data/test.record
Traceback (most recent call last):
  File "generate_tfrecord.py", line 99, in <module>
    tf.app.run()
  File "/home/pi/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "generate_tfrecord.py", line 90, in main
    tf_example = create_tf_example(group, path)
  File "generate_tfrecord.py", line 45, in create_tf_example
    encoded_jpg = fid.read()
  File "/home/pi/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 120, in read
    self._preread_check()
  File "/home/pi/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 80, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/home/pi/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /home/pi/Downloads/new/images/raccoon-1.png; No such file or directory

please help to solve this....
thank you

**Comment by D0o0D** [comment]
i had  the same error, plz help?!

**Comment by Hashirroshan** [comment]
@D0o0D ,
 i think the issues bcz of you have images with png extention . And image format written in generate_tfrecord.py is jpg. so i think due its mismatch some files having png format can convert. so pls verify whether you have all images having jpg format

**Comment by fawadhussain703** [comment]
i have the JPG format images but still having the same error

**Comment by Hashirroshan** [comment]
@fawadhussain703 
check whether u have jpg or png format in generate_tfrecord.py

**Comment by fawadhussain703** [comment]
yes i have resolved this issue by making changes yo xml_to_csv script - 
value = (root.find('filename').text+'.jpg',

**Comment by Aishwarya2203** [comment]
> after following all steps mentioned by dar itran , i got following errors even after put return 0 instead of none.
> 
> pi@pi-HP-280-G1-MT:/Downloads/new$ source activate tensorflow
> (tensorflow) pi@pi-HP-280-G1-MT:/Downloads/new$ python3 generate_tfrecord.py --csv_input=data/test_labels.csv --output_path=data/test.record
> Traceback (most recent call last):
> File "generate_tfrecord.py", line 99, in 
> tf.app.run()
> File "/home/pi/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
> _sys.exit(main(argv))
> File "generate_tfrecord.py", line 90, in main
> tf_example = create_tf_example(group, path)
> File "generate_tfrecord.py", line 45, in create_tf_example
> encoded_jpg = fid.read()
> File "/home/pi/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 120, in read
> self._preread_check()
> File "/home/pi/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 80, in _preread_check
> compat.as_bytes(self.__name), 1024 * 512, status)
> File "/home/pi/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in **exit**
> c_api.TF_GetCode(self.status.status))
> tensorflow.python.framework.errors_impl.NotFoundError: /home/pi/Downloads/new/images/raccoon-1.png; No such file or directory
> 
> please help to solve this....
> thank you

I have JPG format and the images converted to csv are jpg too, also i have replaced the NONE with 0, the problem still persisits

**Comment by kalpalathika** [comment]
solve it yourse\
4
=

**Comment by fawadhussain703** [comment]
> > after following all steps mentioned by dar itran , i got following errors even after put return 0 instead of none.
> > pi@pi-HP-280-G1-MT:/Downloads/new$ source activate tensorflow
> > (tensorflow) pi@pi-HP-280-G1-MT:/Downloads/new$ python3 generate_tfrecord.py --csv_input=data/test_labels.csv --output_path=data/test.record
> > Traceback (most recent call last):
> > File "generate_tfrecord.py", line 99, in
> > tf.app.run()
> > File "/home/pi/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
> > _sys.exit(main(argv))
> > File "generate_tfrecord.py", line 90, in main
> > tf_example = create_tf_example(group, path)
> > File "generate_tfrecord.py", line 45, in create_tf_example
> > encoded_jpg = fid.read()
> > File "/home/pi/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 120, in read
> > self._preread_check()
> > File "/home/pi/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 80, in _preread_check
> > compat.as_bytes(self.__name), 1024 * 512, status)
> > File "/home/pi/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in **exit**
> > c_api.TF_GetCode(self.status.status))
> > tensorflow.python.framework.errors_impl.NotFoundError: /home/pi/Downloads/new/images/raccoon-1.png; No such file or directory
> > please help to solve this....
> > thank you
> 
> I have JPG format and the images converted to csv are jpg too, also i have replaced the NONE with 0, the problem still persisits

Show your Error please???

**Comment by Yogender-Singh** [comment]
should provide the path of image where you store in my case :
python generate_tfrecord.py --csv_input=data/train_labels.csv  --output_path=data/train.record --image_dir=images/

**Comment by Aishwarya2203** [comment]
yes you should provide the full path unless you have the files running from
the same directory
Thanks and Regards,

Aishwarya Murkute.

(424) 381 - 8357 |  murkuteaishwarya@gmail.com

**Comment by tijazz** [comment]
The solution to this is to edit xml_to_csv.py file and remove the concatenation 
`for i in xml_df['filename']:
        names.append(i) + '.jpg'
    xml_df['filename']= names`
Then, edit it to something like this below. Also, remove the concatenation ` value = (root.find('filename').text + '.jpg',` here too.
`for i in xml_df['filename']:
        names.append(i)
    xml_df['filename']= names`

> 
> 
> after following all steps mentioned by dar itran , i got following errors even after put return 0 instead of none.
> 
> pi@pi-HP-280-G1-MT:~/Downloads/new$ source activate tensorflow (tensorflow) pi@pi-HP-280-G1-MT:~/Downloads/new$ python3 generate_tfrecord.py --csv_input=data/test_labels.csv --output_path=data/test.record
> Traceback (most recent call last):
> File "generate_tfrecord.py", line 99, in
> tf.app.run()
> File "/home/pi/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
> _sys.exit(main(argv))
> File "generate_tfrecord.py", line 90, in main
> tf_example = create_tf_example(group, path)
> File "generate_tfrecord.py", line 45, in create_tf_example
> encoded_jpg = fid.read()
> File "/home/pi/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 120, in read
> self._preread_check()
> File "/home/pi/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 80, in _preread_check
> compat.as_bytes(self.__name), 1024 * 512, status)
> File "/home/pi/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in **exit**
> c_api.TF_GetCode(self.status.status))
> tensorflow.python.framework.errors_impl.NotFoundError: /home/pi/Downloads/new/images/raccoon-1.png; No such file or directory
> 
> please help to solve this....
> thank you

**Comment by tijazz** [comment]
The solution to this is to edit xml_to_csv.py file and remove the concatenation
`for i in xml_df['filename']:`
       `names.append(i)+ '.jpg'`
 `xml_df['filename']= names`
Then, edit it to something like this below. Also, remove the concatenation
 `value = (root.find('filename').text + '.jpg',` here too.
`for i in xml_df['filename']:`
       `names.append(i)`
 `xml_df['filename']= names`

![jpgError](https://user-images.githubusercontent.com/21041192/72876142-234b9a00-3cf6-11ea-82ea-99072b553d56.png)
Look at the error and open your test_labels.csv, the filename column, compare it with the Error generated. You can edit the csv file manually and change it ton racoon.png to test the cause..
Goodluck!
