### ISSUE TITLE
error with generate_tfrecord.py 

### ISSUE THREAD

**Issue by D0o0D** [datitran/raccoon_dataset#65]
this is code with my edits

`"""
Usage:
  # From tensorflow/models/
  # Create train data:
  python generate_tfrecord.py --csv_input=E:/projectx/object-detection/train_labels.csv  --output_path=train.record
  # Create test data:
  python generate_tfrecord.py --csv_input=E:/projectx/object-detection/test_labels.csv  --output_path=test.record
"""
from __future__ import division
from __future__ import print_function
from __future__ import absolute_import

import os
import io
import pandas as pd
import tensorflow as tf

from PIL import Image
from object_detection.utils import dataset_util
from collections import namedtuple, OrderedDict

flags = tf.app.flags
flags.DEFINE_string('csv_input', '', 'E:/projectx/object-detection/')
flags.DEFINE_string('output_path', '', 'E:/projectx/object-detection/')
FLAGS = flags.FLAGS

# TO-DO replace this with label map
def class_text_to_int(row_label):
    if row_label == 'cyst':
        return 1
    else:
        None

def split(df, group):
    data = namedtuple('data', ['filename', 'object'])
    gb = df.groupby(group)
    return [data(filename, gb.get_group(x)) for filename, x in zip(gb.groups.keys(), gb.groups)]

def create_tf_example(group, path):
    with tf.gfile.GFile(os.path.join(path, '{}'.format(group.filename)), 'rb') as fid:
        encoded_jpg = fid.read()
    encoded_jpg_io = io.BytesIO(encoded_jpg)
    image = Image.open(encoded_jpg_io)
    width, height = image.size

    filename = group.filename.encode('utf8')
    image_format = b'jpg'
    xmins = []
    xmaxs = []
    ymins = []
    ymaxs = []
    classes_text = []
    classes = []

    for index, row in group.object.iterrows():
        xmins.append(row['xmin'] / width)
        xmaxs.append(row['xmax'] / width)
        ymins.append(row['ymin'] / height)
        ymaxs.append(row['ymax'] / height)
        classes_text.append(row['class'].encode('utf8'))
        classes.append(class_text_to_int(row['class']))

    tf_example = tf.train.Example(features=tf.train.Features(feature={
        'image/height': dataset_util.int64_feature(height),
        'image/width': dataset_util.int64_feature(width),
        'image/filename': dataset_util.bytes_feature(filename),
        'image/source_id': dataset_util.bytes_feature(filename),
        'image/encoded': dataset_util.bytes_feature(encoded_jpg),
        'image/format': dataset_util.bytes_feature(image_format),
        'image/object/bbox/xmin': dataset_util.float_list_feature(xmins),
        'image/object/bbox/xmax': dataset_util.float_list_feature(xmaxs),
        'image/object/bbox/ymin': dataset_util.float_list_feature(ymins),
        'image/object/bbox/ymax': dataset_util.float_list_feature(ymaxs),
        'image/object/class/text': dataset_util.bytes_list_feature(classes_text),
        'image/object/class/label': dataset_util.int64_list_feature(classes),
    }))
    return tf_example

def main(_):
    writer = tf.python_io.TFRecordWriter(FLAGS.output_path)
    path = os.path.join(os.getcwd(), 'images')
    examples = pd.read_csv(FLAGS.csv_input)
    grouped = split(examples, 'filename')
    for group in grouped:
        tf_example = create_tf_example(group, path)
        writer.write(tf_example.SerializeToString())

    writer.close()
    output_path = os.path.join(os.getcwd(), FLAGS.output_path)
    print('Successfully created the TFRecords: {}'.format(output_path))

if __name__ == '__main__':
    tf.app.run()`

problem :- 

`Traceback (most recent call last):
  File "E:/projectx/object-detection/generate_tfrecord.py", line 98, in <module>
    tf.app.run()
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "E:/projectx/object-detection/generate_tfrecord.py", line 84, in main
    writer = tf.python_io.TFRecordWriter(FLAGS.output_path)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\lib\io\tf_record.py", line 112, in __init__
    compat.as_bytes(path), compat.as_bytes(compression_type), status)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a NewWriteableFile:  : The system cannot find the path specified.
; No such process`

i don't know what exactly this error?
please help 
thanks,
Dod

**Comment by s-buschmann** [comment]
Hi guys, I had the same issue. My issue was that I didn't have pandas installed in the current activated environment. After installing pandas, I then navigated to the directory of the generate_tfrecord.py file and ran it from the console with the command line arguments found at the top of the file ie: "python generate_tfrecord.py --csv_input=data/train_labels.csv  --output_path=train.record"
I hope this helps. Goodluck!

**Comment by vinamramattoo** [comment]
I was getting 
`File "/home/vinamra/anaconda3/envs/tcpu/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: raccoon-1.jpg; No such file or directory
`

I could solve this by running `python generate_tfrecord.py --csv_input=data/train_labels.csv --output_path=train.record --image_dir=./images`

**Comment by Nikh1l** [comment]
> I was getting
> `File "/home/vinamra/anaconda3/envs/tcpu/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__ c_api.TF_GetCode(self.status.status)) tensorflow.python.framework.errors_impl.NotFoundError: raccoon-1.jpg; No such file or directory `
> 
> I could solve this by running `python generate_tfrecord.py --csv_input=data/train_labels.csv --output_path=train.record --image_dir=./images`

Same here. Thanks for the solution XD

**Comment by Vaerysse** [comment]
> I was getting
> `File "/home/vinamra/anaconda3/envs/tcpu/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__ c_api.TF_GetCode(self.status.status)) tensorflow.python.framework.errors_impl.NotFoundError: raccoon-1.jpg; No such file or directory `
> 
> I could solve this by running `python generate_tfrecord.py --csv_input=data/train_labels.csv --output_path=train.record --image_dir=./images`

Thx is ok for me!!!

**Comment by bhaktiparanjape** [comment]
22 for index, row in group.object.iterrows():
     23   xmins.append(row['xmin'] / width)
     24   xmaxs.append(row['xmax'] / width)

NameError: name 'group' is not defined

This is the error i am getting. Pl help

**Comment by Sammanifer123** [comment]
l was getting error like this in generate_tfrecord.py file.
File "/mydrive/customTF2/generate_tfrecord.py", line 137, in <module>
    tf_example = create_tf_example(group, path, class_dict)
  File "/mydrive/customTF2/generate_tfrecord.py", line 57, in create_tf_example
    classes.append(class_dict[str(row['class'])])
KeyError: 'dog'
