### ISSUE TITLE
unable to run the code locally in Mac

### ISSUE THREAD

**Issue by kmenita** [datitran/raccoon_dataset#71]
I am trying run the code locally in my mac and I m getting error. 

I have changed the config file , and while running the train command I am getting the issue. 

Config file setup: 
fine_tune_checkpoint: "/Users/kmenita/Downloads/venky_project/ssd_mobilenet_v1/model.ckpt"
input_path: "/Users/kmenita/Downloads/venky_project/raccoon/data/train.record"
label_map_path: "/Users/kmenita/Downloads/venky_project/raccoon/training/object-detection.pbtxt"
input_path: "/Users/kmenita/Downloads/venky_project/raccoon/data/test.record"
label_map_path: "/Users/kmenita/Downloads/venky_project/raccoon/training/object-detection.pbtxt"

Final code to execute the training:

PIPELINE_CONFIG_PATH=“/Users/kmenita/Downloads/venky_project/raccoon/training/ssd_mobilenet_v1_pets.config”
MODEL_DIR=“/Users/kmenita/Downloads/venky_project/raccoon/training”
NUM_TRAIN_STEPS=50000
SAMPLE_1_OF_N_EVAL_EXAMPLES=1

python object_detection/model_main.py \ --PIPELINE_CONFIG_PATH=“/Users/kmenita/Downloads/venky_project/raccoon/training/ssd_mobilenet_v1_pets.config” \ --MODEL_DIR=“/Users/kmenita/Downloads/venky_project/raccoon/training” \ --num_train_steps=5000 \ -- sample_1_of_n_eval_examples=1 \ --alsologtostderr

Error Message 

  import matplotlib; matplotlib.use('Agg')  # pylint: disable=multiple-statements
Traceback (most recent call last):
  File "object_detection/model_main.py", line 109, in <module>
    tf.app.run()
  File "/Users/kmenita/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "object_detection/model_main.py", line 71, in main
    FLAGS.sample_1_of_n_eval_on_train_examples))
  File "/Users/kmenita/Downloads/venky_project/models/research/object_detection/model_lib.py", line 525, in create_estimator_and_inputs
    configs = get_configs_from_pipeline_file(pipeline_config_path)
  File "/Users/kmenita/Downloads/venky_project/models/research/object_detection/utils/config_util.py", line 93, in get_configs_from_pipeline_file
    proto_str = f.read()
  File "/Users/kmenita/anaconda3/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 125, in read
    self._preread_check()
  File "/Users/kmenita/anaconda3/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 85, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/Users/kmenita/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/compat.py", line 61, in as_bytes
    (bytes_or_text,))
TypeError: Expected binary or unicode string, got None

please advice

**Comment by vojavocni** [comment]
I also have the same problem on Ubuntu 16.04. I have no idea what's wrong with FLAGS.sample_1_of_n_eval_on_train_examples...

**Comment by brannonbarr** [comment]
I'm having the same issue on Windows 7, someone please advise.
