### ISSUE TITLE
unable to run generate_tfrecord.py in Anaconda

### ISSUE THREAD

**Issue by drhooray** [datitran/raccoon_dataset#72]
env: windows7 
conda : 4.5.4

I execute the following command, it will fail and jump out "TypeError".

$ python generate_tfrecord.py --csv_input=clothes_labels.csv --output_path=clothes_test.record

========================
Traceback (most recent call last):
  File "generate_tfrecord.py", line 100, in <module>
    tf.app.run()
  File "C:\Users\jason\Anaconda2\envs\venv_demo\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
. . .
  File "C:\Users\jason\Anaconda2\envs\venv_demo\lib\site-packages\google\protobuf\internal\containers.py", line 275, in <listcomp>
    new_values = [self._type_checker.CheckValue(elem) for elem in elem_seq_iter]
  File "C:\Users\jason\Anaconda2\envs\venv_demo\lib\site-packages\google\protobuf\internal\type_checkers.py", line 133, in CheckValue
    raise TypeError(message)
TypeError: None has type <class 'NoneType'>, but expected one of: (<class 'int'>,)
=======================================

have any ideas?
thanks

**Comment by venkateshbabusekar** [comment]
I am also facing the same issue ,  can you please help with it 


(tensorflow2) C:\tensorflow2\models\research\object_detection>python generate_tfrecord.py --csv_input=images\train_labels.csv --image_dir=images\train --output_path=train.record
Traceback (most recent call last):
  File "generate_tfrecord.py", line 100, in <module>
    tf.app.run()
  File "C:\Users\babus\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "generate_tfrecord.py", line 91, in main
    tf_example = create_tf_example(group, path)
  File "generate_tfrecord.py", line 80, in create_tf_example
    'image/object/class/label': dataset_util.int64_list_feature(classes),
  File "C:\Users\babus\Anaconda3\envs\tensorflow2\lib\site-packages\object_detection-0.1-py3.5.egg\object_detection\utils\dataset_util.py", line 26, in int64_list_feature
    return tf.train.Feature(int64_list=tf.train.Int64List(value=value))
TypeError: None has type NoneType, but expected one of: int, long
